### ISSUE TITLE
Bundle Identifier Incorrect

### ISSUE THREAD

**Issue by nescroft** [ramyareye/react-native-eject#2]
The bundle identifier does not seem to be the same as the one specified in app.json

**Comment by ramyareye** [comment]
@nescroft I copied this package as it was in react-native-cli and there wasn't such thing.
right now I made a look on options exist and found [this package](https://github.com/kyle-ssg/react-native-app-id) but seems it doesn't work as expected
[here](https://stackoverflow.com/questions/36119754/how-to-change-the-bundle-identifier-within-react-native) I found a guide to do it and I thought to provide it as an option like -b or if it exists in app.json
so I try to make it work by the next week or will be happy with a PR XD
