### ISSUE TITLE
Cannot find module '@react-native-community/cli/build/tools/generator/copyProjectTemplateAndReplace'

### ISSUE THREAD

**Issue by aqeebimtiaz** [ramyareye/react-native-eject#4]
I tried to install this package to rename my project and I got this error:
**error Cannot find module '@react-native-community/cli/build/tools/generator/copyProjectTemplateAndReplace'.**

Tried deleting **package-lock.json** & **node_modules** and reinstalling using **npm install**. Still same error.

**Comment by themaxsandelin** [comment]
Having the same issue. 😔

**Comment by ramyareye** [comment]
@aqeebimtiaz @themaxsandelin please tell me your rn and rn-cli version and if you're using local react-native command or npx?

**Comment by themaxsandelin** [comment]
I'm running `react-native` version 4.10.0 installed globally on my machine and npm installed `react-native-eject`.

**Comment by ramyareye** [comment]
@themaxsandelin I don't really know what's wrong in your case :) I just tried these commands and worked!

`npx react-native init AwesomeProject`
`cd AwesomeProject &&  npx react-native run-ios`

then eject
`rm -rf ios android`
`yarn add react-native-eject`
`npx react-native eject`
`cd ios && pod install && cd ..`
`npx react-native run-ios`

thiis all just worked

**Comment by aqeebimtiaz** [comment]
I'm not entirely sure about installing on a fresh new project. I was trying to use this package on an existing project at my office.

> @aqeebimtiaz @themaxsandelin please tell me your rn and rn-cli version and if you're using local react-native command or npx?

I'm using `react-native-cli: 2.0.1` & `react-native: 0.61.2` running locally.

**Comment by ramyareye** [comment]
I just tried with a `0.61.5` project and worked well.
possible to try it with `yarn react-native eject` or `npx react-native eject`?

**Comment by samitha9125** [comment]
@ramyareye Nope. Still this error occurs for even 0.63.2.

**Comment by samitha9125** [comment]
After digging deeper, I found that `@react-native-community/cli` does not exist anymore in cli that get installed with react native init. However if you need to use this package, then just do the followings.

1. Install[ @react-native-community/cli](https://www.npmjs.com/package/@react-native-community/cli) (This is already installed with React native itself but you cannot find it in the package.json and you cannot/should not use it as you like. However you have to install this in your project root until @ramyareye or someone else finds a solution :) )
2. Then perform npx react-native eject after deleting ios and android folders (Remember to change your project name to the latest one in the app.json)
3. Now you will get iOS and Android folders as expected. 
4. You can remove the @react-native-community/cli now if you want (This will just remove what you installed. Will not harm the cli that React Native itself installed)

**Comment by dzantiev** [comment]
run `npm i --save-dev @react-native-community/cli`

**Comment by JacobDel** [comment]
Did not work: https://github.com/ramyareye/react-native-eject/issues/6
