### ISSUE TITLE
eject not working: Cannot find module 'copyProjectTemplateAndReplace'

### ISSUE THREAD

**Issue by JacobDel** [ramyareye/react-native-eject#6]
npm packages:
- +-- react-native-eject@0.1.2
- +-- react-native-cli@2.0.1

`
C:\Users\User 1\desktop\project>npx react-native eject
error Cannot find module '@react-native-community/cli/build/tools/generator/copyProjectTemplateAndReplace'
Require stack:
- C:\Users\User 1\desktop\project\node_modules\react-native-eject\build\eject.js
- C:\Users\User 1\desktop\project\node_modules\react-native-eject\react-native.config.js
- C:\Users\User 1\desktop\project\node_modules\cosmiconfig\node_modules\import-fresh\index.js
- C:\Users\User 1\desktop\project\node_modules\cosmiconfig\dist\loaders.js
- C:\Users\User 1\desktop\project\node_modules\cosmiconfig\dist\createExplorer.js
- C:\Users\User 1\desktop\project\node_modules\cosmiconfig\dist\index.js
- C:\Users\User 1\desktop\project\node_modules\@react-native-community\cli-config\build\readConfigFromDisk.js
- C:\Users\User 1\desktop\project\node_modules\@react-native-community\cli-config\build\loadConfig.js
- C:\Users\User 1\desktop\project\node_modules\@react-native-community\cli-config\build\index.js
- C:\Users\User 1\desktop\project\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\index.js
- C:\Users\User 1\desktop\project\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js
- C:\Users\User 1\desktop\project\node_modules\react-native\cli.js.
Error: Cannot find module '@react-native-community/cli/build/tools/generator/copyProjectTemplateAndReplace'
Require stack:
- C:\Users\User 1\desktop\project\node_modules\react-native-eject\build\eject.js
- C:\Users\User 1\desktop\project\node_modules\react-native-eject\react-native.config.js
- C:\Users\User 1\desktop\project\node_modules\cosmiconfig\node_modules\import-fresh\index.js
- C:\Users\User 1\desktop\project\node_modules\cosmiconfig\dist\loaders.js
- C:\Users\User 1\desktop\project\node_modules\cosmiconfig\dist\createExplorer.js
- C:\Users\User 1\desktop\project\node_modules\cosmiconfig\dist\index.js
- C:\Users\User 1\desktop\project\node_modules\@react-native-community\cli-config\build\readConfigFromDisk.js
- C:\Users\User 1\desktop\project\node_modules\@react-native-community\cli-config\build\loadConfig.js
- C:\Users\User 1\desktop\project\node_modules\@react-native-community\cli-config\build\index.js
- C:\Users\User 1\desktop\project\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\index.js
- C:\Users\User 1\desktop\project\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js
- C:\Users\User 1\desktop\project\node_modules\react-native\cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:955:15)
    at Module._load (node:internal/modules/cjs/loader:803:27)
    at Module.require (node:internal/modules/cjs/loader:1021:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\User 1\desktop\project\node_modules\react-native-eject\build\eject.js:15:38)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
    at Module.require (node:internal/modules/cjs/loader:1021:19)
info Run CLI with --verbose flag for more details.

`

Yarn packages:
-     "@react-native-community/cli": "^9.3.2",
-     "react-native-eject": "^0.1.2",
-     "react-native": "0.70.5",
Same error:
`
>react-native eject
error Cannot find module '@react-native-community/cli/build/tools/generator/copyProjectTemplateAndReplace'
....
`

**Comment by ramyareye** [comment]
@JacobDel it's happening cause they removed some files in [here](https://github.com/react-native-community/cli/pull/1644)
I'll try to import them in project and make it work

**Comment by peterasorensen** [comment]
Just checking in, any updates here? Same issue for me.

**Comment by peterasorensen** [comment]
Actually I was able to get around this by using an old version. @JacobDel if you still have the issue:

```
npm install @react-native-community/cli@8.0.0

react-native eject
```
